import NavbarComponent from "@/components/NavbarComponent";
import SidebarComponent from "@/components/SidebarComponent";
import "./globals.css";
import ListBoardComponentHeader from "@/components/ListBoardComponentHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <div className="flex justify-between">
          <div className="w-[18%]">
            <SidebarComponent />
          </div>
          <div className="w-[80%]">
            <div>
              <NavbarComponent />
            </div>
            <div className="w-full">{/* <ListBoardComponentHeader /> */}</div>

            <img
              src="../assets/icons/welcome.jpg"
              alt="welcome image"
              className=""
            />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
